"""Skill file generation endpoint.

Generates a personalized Markdown AI skill file from a simple questionnaire.
Can be used without login (for demos / hackathons).
有機農業（自然栽培を含む）専用。
"""

import json
from fastapi import APIRouter
from pydantic import BaseModel

router = APIRouter(prefix="/skillfile", tags=["skillfile"])

# -- 4軸の選択肢 --

FERTILIZER_OPTIONS = {
    "none": "無施肥（自然の循環のみ）",
    "compost": "堆肥（植物性・動物性）",
    "green_manure": "緑肥（すき込み）",
    "bokashi": "ぼかし肥料",
}

PESTICIDE_OPTIONS = {
    "none": "無農薬",
    "organic_certified": "有機JAS認定資材のみ",
}

TILLAGE_OPTIONS = {
    "no_till": "不耕起",
    "minimum_till": "部分耕起",
    "till": "耕起",
}

COVER_OPTIONS = {
    "grass": "草生栽培",
    "mulch": "マルチ（敷きわら等）",
    "cover_crop": "カバークロップ",
    "none": "被覆なし",
}

EXPERIENCE_LEVELS = {
    "beginner": "初心者（1年未満）",
    "intermediate": "中級者（1〜3年）",
    "experienced": "経験者（3〜10年）",
    "expert": "熟練者（10年以上）",
}

# 旧形式の農法名を4軸に変換
_LEGACY_MAP = {
    "natural": {"fertilizer": "none", "pesticide": "none", "tillage": "no_till", "cover": "grass"},
    "organic": {"fertilizer": "compost", "pesticide": "none", "tillage": "till", "cover": "mulch"},
    "permaculture": {"fertilizer": "green_manure", "pesticide": "none", "tillage": "no_till", "cover": "cover_crop"},
}


class SkillFileRequest(BaseModel):
    crops: list[str]
    location: str
    # 新しい4軸形式
    fertilizer: str = ""
    pesticide: str = ""
    tillage: str = ""
    cover: str = ""
    # 旧互換
    farming_method: str = ""
    experience: str
    challenges: str = ""


class SkillFileResponse(BaseModel):
    skill_file: str
    system_prompt: str


def _resolve_practices(req: SkillFileRequest) -> dict:
    """リクエストから4軸の値を解決する。旧形式にも対応"""
    if req.fertilizer or req.pesticide or req.tillage or req.cover:
        return {
            "fertilizer": req.fertilizer,
            "pesticide": req.pesticide,
            "tillage": req.tillage,
            "cover": req.cover,
        }
    # 旧形式からの変換
    fm = req.farming_method
    if fm.startswith("{"):
        try:
            return json.loads(fm)
        except json.JSONDecodeError:
            pass
    if fm in _LEGACY_MAP:
        return _LEGACY_MAP[fm]
    return {"fertilizer": "", "pesticide": "", "tillage": "", "cover": ""}


def _practices_display(p: dict) -> str:
    """4軸の値を表示用文字列に変換"""
    parts = []
    f = FERTILIZER_OPTIONS.get(p.get("fertilizer", ""))
    if f:
        parts.append(f)
    ps = PESTICIDE_OPTIONS.get(p.get("pesticide", ""))
    if ps:
        parts.append(ps)
    t = TILLAGE_OPTIONS.get(p.get("tillage", ""))
    if t:
        parts.append(t)
    c = COVER_OPTIONS.get(p.get("cover", ""))
    if c:
        parts.append(c)
    return "・".join(parts) if parts else "未設定"


def _generate_skill_file(req: SkillFileRequest) -> str:
    p = _resolve_practices(req)
    lines = []
    lines.append("# 栽培AIスキルファイル\n")
    lines.append("> このファイルをAIアシスタントのシステムプロンプトや")
    lines.append("> カスタム指示に貼り付けると、あなた専用の栽培アドバイザーになります。")
    lines.append("> Generated by AIseed Grow（有機農業専用）\n")

    lines.append("## あなたの役割\n")
    lines.append("あなたは有機農業（自然栽培を含む）の専門家アシスタントです。")
    lines.append("化学合成農薬・化学肥料の使用は一切提案しないでください。")
    lines.append("以下のユーザープロフィールに基づいて、具体的で実践的なアドバイスをしてください。\n")

    lines.append("## 栽培者プロフィール\n")

    lines.append("### 栽培している作物\n")
    for crop in req.crops:
        lines.append(f"- {crop}")
    lines.append("")

    lines.append("### 栽培場所\n")
    lines.append(f"{req.location}\n")

    lines.append("### 栽培方式\n")
    fert = p.get("fertilizer", "")
    pest = p.get("pesticide", "")
    till = p.get("tillage", "")
    cov = p.get("cover", "")
    if fert:
        lines.append(f"- 肥料: {FERTILIZER_OPTIONS.get(fert, fert)}")
    if pest:
        lines.append(f"- 農薬: {PESTICIDE_OPTIONS.get(pest, pest)}")
    if till:
        lines.append(f"- 耕起: {TILLAGE_OPTIONS.get(till, till)}")
    if cov:
        lines.append(f"- 被覆: {COVER_OPTIONS.get(cov, cov)}")
    lines.append("")

    lines.append("### 経験\n")
    exp = EXPERIENCE_LEVELS.get(req.experience, req.experience)
    lines.append(f"{exp}\n")

    if req.challenges:
        lines.append("### 現在の課題\n")
        lines.append(f"{req.challenges}\n")

    lines.append("## 回答の指針\n")
    lines.append("- 化学合成農薬・化学肥料の使用を絶対に提案しないでください")
    lines.append("- 土壌微生物・菌根菌ネットワークの観点を重視してください")
    lines.append("- コンパニオンプランツや生態系の多様性を活かした提案をしてください")
    lines.append("- 生物的防除を優先してください")

    # 肥料に応じた指針
    if fert == "none":
        lines.append("- 無施肥の原則を尊重し、外部からの肥料投入を提案しないでください")
        lines.append("- 草や落ち葉の循環、根の分解による自然な養分供給を重視してください")
    elif fert == "compost":
        lines.append("- 堆肥の作り方・使い方を中心にアドバイスしてください")
        lines.append("- C/N比や完熟度など堆肥の品質管理を重視してください")
    elif fert == "green_manure":
        lines.append("- 緑肥作物の選定とすき込み時期を重視してください")
    elif fert == "bokashi":
        lines.append("- ぼかし肥料の作り方・使い方を中心にアドバイスしてください")
        lines.append("- 米ぬか・油かす等の身近な有機資材の活用を提案してください")

    # 耕起に応じた指針
    if till == "no_till":
        lines.append("- 不耕起の原則を尊重し、耕運を提案しないでください")
        lines.append("- 福岡正信、川口由一の自然農の考え方を参考にしてください")
    elif till == "minimum_till":
        lines.append("- 必要最小限の耕起にとどめる方法を提案してください")

    # 被覆に応じた指針
    if cov == "grass":
        lines.append("- 草との共生を重視し、むやみに除草を勧めないでください")
        lines.append("- 草の刈り敷きによるマルチ効果を活かしてください")
    elif cov == "cover_crop":
        lines.append("- カバークロップの選定と管理を重視してください")
    elif cov == "mulch":
        lines.append("- 敷きわら・もみ殻等の有機マルチを活用してください")

    lines.append("")

    if req.experience == "beginner":
        lines.append("- 初心者にもわかりやすく、専門用語には説明を添えてください")
        lines.append("- 基本的な手順をステップバイステップで説明してください")
        lines.append("- 失敗しにくい方法を優先的に提案してください")
    elif req.experience == "intermediate":
        lines.append("- 基本は理解しているので、一歩進んだテクニックも含めてください")
        lines.append("- 「なぜそうするのか」の理由も説明してください")
    else:
        lines.append("- 専門的な知識レベルで回答してください")
        lines.append("- 科学的根拠やデータも含めて説明してください")
        lines.append("- 新しい研究結果や革新的な手法も紹介してください")

    lines.append("")

    lines.append("## 日本野菜とイタリア野菜の知識\n")
    lines.append("ユーザーが「柔らかくてみずみずしい野菜を作りたい」と言った場合、")
    lines.append("土壌や気候条件によっては難しいことがあります。以下の知識を活用してください。\n")
    lines.append("### 重要な視点の転換")
    lines.append("- 硬い野菜＝失敗ではない。イタリア野菜の視点では「旨味が凝縮」している")
    lines.append("- 粘土質土壌・乾燥地は日本野菜には不向きだが、地中海野菜には理想的")
    lines.append("- 土を変えるより、土に合った作物と調理法を選ぶ方が賢明\n")
    lines.append("### 土壌・気候が厳しい場合のおすすめ作物")
    lines.append("- アーティチョーク（深根性、菌根菌共生、多年草）")
    lines.append("- チコリ・エンダイブ（キク科、低窒素適応）")
    lines.append("- カボチャ・ズッキーニ（乾燥耐性、菌根菌共生）")
    lines.append("- トマト・ナス（水を控えると味が濃くなる）")
    lines.append("- ルッコラ（辛味と苦味が特徴）\n")
    lines.append("### 科学的背景")
    lines.append("- イタリア野菜は乾燥ストレスで糖・ポリフェノール・グルタミン酸を蓄積する")
    lines.append("- ペクチンが多いため加熱で「トロトロ」に軟化する（リグニンで硬くなる日本野菜と異なる）")
    lines.append("- 菌根菌と共生する科（キク科・ナス科・ウリ科）は痩せ地でも旨味を作れる")
    lines.append("- アブラナ科・アカザ科（日本の葉物）は菌根菌と共生せず高窒素が必要\n")
    lines.append("### 調理法も一緒に提案する")
    lines.append("- 硬い野菜はオリーブオイルでじっくり加熱すると旨味が引き出される")
    lines.append("- 苦味はアク抜きせず、油脂と合わせると深みに変わる")
    lines.append("- 日本料理の調理法（生食・軽い加熱）は柔らかい日本野菜向け")
    lines.append("")

    lines.append("## 一般的な注意事項\n")
    lines.append("- 日本語で回答してください")
    lines.append("- 季節や気候を考慮した具体的なアドバイスをしてください")
    lines.append("- 可能であれば、具体的な時期（月や旬）を示してください")
    lines.append("- 不確かな情報は推測であることを明記してください")
    lines.append("")

    return "\n".join(lines)


def _generate_system_prompt(req: SkillFileRequest) -> str:
    p = _resolve_practices(req)
    exp = EXPERIENCE_LEVELS.get(req.experience, req.experience)
    crops = "、".join(req.crops)
    display = _practices_display(p)

    parts = [
        "あなたは有機農業（自然栽培を含む）の専門家コワーカーです。",
        "化学合成農薬・化学肥料は一切提案しないでください。",
        "",
        f"ユーザー: {exp}。",
        f"栽培方式: {display}",
        f"栽培作物: {crops}",
        f"場所: {req.location}",
    ]
    if req.challenges:
        parts.append(f"課題: {req.challenges}")
    parts.append("")
    parts.append("具体的で実践的なアドバイスを日本語で回答してください。")

    fert = p.get("fertilizer", "")
    till = p.get("tillage", "")
    cov = p.get("cover", "")

    if fert == "none":
        parts.append("無施肥の原則を尊重してください。")
    if till == "no_till":
        parts.append("不耕起の原則を尊重してください。")
    if cov == "grass":
        parts.append("草生栽培の原則を尊重してください。")

    parts.append("")
    parts.append("重要: 柔らかい日本野菜が育ちにくい土壌・気候の場合、イタリア野菜（地中海野菜）への転換を提案してください。")
    parts.append("硬い野菜は失敗ではなく、オリーブオイルで加熱すれば旨味が凝縮した野菜です。")
    parts.append("粘土質・乾燥地にはアーティチョーク、チコリ、カボチャ等が適しています。")
    parts.append("調理法も一緒に提案してください。")

    return "\n".join(parts)


@router.post("/generate", response_model=SkillFileResponse)
async def generate_skill_file(req: SkillFileRequest):
    """Generate a personalized Markdown skill file.

    No login required - works for demos and hackathons.
    """
    return SkillFileResponse(
        skill_file=_generate_skill_file(req),
        system_prompt=_generate_system_prompt(req),
    )
