/// Generates a personalized cultivation AI skill file (Markdown)
/// based on user's answers to 5 simple questions.

class GrowProfile {
  final List<String> crops;
  final String location;
  final String farmingMethod;
  final String experience;
  final String challenges;

  GrowProfile({
    required this.crops,
    required this.location,
    required this.farmingMethod,
    required this.experience,
    required this.challenges,
  });

  Map<String, dynamic> toMap() => {
        'crops': crops,
        'location': location,
        'farming_method': farmingMethod,
        'experience': experience,
        'challenges': challenges,
      };
}

class SkillFileGenerator {
  static const farmingMethods = {
    'natural': '自然農（不耕起・無施肥・無農薬）',
    'organic': '有機農業（有機肥料・無農薬）',
    'conventional': '慣行農業',
    'permaculture': 'パーマカルチャー',
    'other': 'その他',
  };

  static const experienceLevels = {
    'beginner': '初心者（1年未満）',
    'intermediate': '中級者（1〜3年）',
    'experienced': '経験者（3〜10年）',
    'expert': '熟練者（10年以上）',
  };

  /// Generate a Markdown skill file from the user profile.
  static String generate(GrowProfile profile) {
    final buf = StringBuffer();

    buf.writeln('# 栽培AIスキルファイル');
    buf.writeln();
    buf.writeln('> このファイルをAIアシスタントのシステムプロンプトや');
    buf.writeln('> カスタム指示に貼り付けると、あなた専用の栽培アドバイザーになります。');
    buf.writeln('> Generated by AIseed Grow');
    buf.writeln();

    // Role definition
    buf.writeln('## あなたの役割');
    buf.writeln();
    buf.writeln('あなたは栽培の専門家アシスタントです。');
    buf.writeln('以下のユーザープロフィールに基づいて、具体的で実践的なアドバイスをしてください。');
    buf.writeln();

    // User profile
    buf.writeln('## 栽培者プロフィール');
    buf.writeln();

    // Crops
    buf.writeln('### 栽培している作物');
    buf.writeln();
    for (final crop in profile.crops) {
      buf.writeln('- $crop');
    }
    buf.writeln();

    // Location
    buf.writeln('### 栽培場所');
    buf.writeln();
    buf.writeln(profile.location);
    buf.writeln();

    // Farming method
    buf.writeln('### 農法');
    buf.writeln();
    final methodLabel =
        farmingMethods[profile.farmingMethod] ?? profile.farmingMethod;
    buf.writeln(methodLabel);
    buf.writeln();

    // Experience
    buf.writeln('### 経験');
    buf.writeln();
    final expLabel =
        experienceLevels[profile.experience] ?? profile.experience;
    buf.writeln(expLabel);
    buf.writeln();

    // Challenges
    if (profile.challenges.isNotEmpty) {
      buf.writeln('### 現在の課題');
      buf.writeln();
      buf.writeln(profile.challenges);
      buf.writeln();
    }

    // Instructions based on farming method
    buf.writeln('## 回答の指針');
    buf.writeln();

    switch (profile.farmingMethod) {
      case 'natural':
        buf.writeln('- 自然農の原則（不耕起・無施肥・無農薬・草との共生）を尊重してください');
        buf.writeln('- 化学肥料や農薬の使用を提案しないでください');
        buf.writeln('- 土壌微生物・菌根菌ネットワークの観点を重視してください');
        buf.writeln('- コンパニオンプランツや生態系の多様性を活かした提案をしてください');
        buf.writeln('- 福岡正信、川口由一の自然農の考え方を参考にしてください');
        break;
      case 'organic':
        buf.writeln('- 有機JAS基準に準拠したアドバイスをしてください');
        buf.writeln('- 化学合成農薬・化学肥料の使用を提案しないでください');
        buf.writeln('- 堆肥、緑肥、有機質肥料を活用した提案をしてください');
        buf.writeln('- 生物的防除やコンパニオンプランツを優先してください');
        break;
      case 'permaculture':
        buf.writeln('- パーマカルチャーの倫理（地球への配慮・人への配慮・余剰の共有）を基本にしてください');
        buf.writeln('- 多年生植物、フォレストガーデン、ギルドの概念を取り入れてください');
        buf.writeln('- 水の循環、エネルギー効率、生態系デザインを考慮してください');
        break;
      default:
        buf.writeln('- 効率と品質のバランスを考えた実践的なアドバイスをしてください');
        buf.writeln('- 農薬使用時は適切な使用量と安全な使用方法を明記してください');
    }

    buf.writeln();

    // Experience-based tone
    switch (profile.experience) {
      case 'beginner':
        buf.writeln('- 初心者にもわかりやすく、専門用語には説明を添えてください');
        buf.writeln('- 基本的な手順をステップバイステップで説明してください');
        buf.writeln('- 失敗しにくい方法を優先的に提案してください');
        break;
      case 'intermediate':
        buf.writeln('- 基本は理解しているので、一歩進んだテクニックも含めてください');
        buf.writeln('- 「なぜそうするのか」の理由も説明してください');
        break;
      case 'experienced':
      case 'expert':
        buf.writeln('- 専門的な知識レベルで回答してください');
        buf.writeln('- 科学的根拠やデータも含めて説明してください');
        buf.writeln('- 新しい研究結果や革新的な手法も紹介してください');
        break;
    }

    buf.writeln();

    // Vegetable knowledge base
    buf.writeln('## 日本野菜とイタリア野菜の知識');
    buf.writeln();
    buf.writeln('ユーザーが「柔らかくてみずみずしい野菜を作りたい」と言った場合、');
    buf.writeln('土壌や気候条件によっては難しいことがあります。以下の知識を活用してください。');
    buf.writeln();
    buf.writeln('### 重要な視点の転換');
    buf.writeln('- 硬い野菜＝失敗ではない。イタリア野菜の視点では「旨味が凝縮」している');
    buf.writeln('- 粘土質土壌・乾燥地は日本野菜には不向きだが、地中海野菜には理想的');
    buf.writeln('- 土を変えるより、土に合った作物と調理法を選ぶ方が賢明');
    buf.writeln();
    buf.writeln('### 土壌・気候が厳しい場合のおすすめ作物');
    buf.writeln('- アーティチョーク（深根性、菌根菌共生、多年草）');
    buf.writeln('- チコリ・エンダイブ（キク科、低窒素適応）');
    buf.writeln('- カボチャ・ズッキーニ（乾燥耐性、菌根菌共生）');
    buf.writeln('- トマト・ナス（水を控えると味が濃くなる）');
    buf.writeln('- ルッコラ（辛味と苦味が特徴）');
    buf.writeln();
    buf.writeln('### 科学的背景');
    buf.writeln('- イタリア野菜は乾燥ストレスで糖・ポリフェノール・グルタミン酸を蓄積する');
    buf.writeln('- ペクチンが多いため加熱で「トロトロ」に軟化する（リグニンで硬くなる日本野菜と異なる）');
    buf.writeln('- 菌根菌と共生する科（キク科・ナス科・ウリ科）は痩せ地でも旨味を作れる');
    buf.writeln('- アブラナ科・アカザ科（日本の葉物）は菌根菌と共生せず高窒素が必要');
    buf.writeln();
    buf.writeln('### 調理法も一緒に提案する');
    buf.writeln('- 硬い野菜はオリーブオイルでじっくり加熱すると旨味が引き出される');
    buf.writeln('- 苦味はアク抜きせず、油脂と合わせると深みに変わる');
    buf.writeln('- 日本料理の調理法（生食・軽い加熱）は柔らかい日本野菜向け');
    buf.writeln();

    // General guidelines
    buf.writeln('## 一般的な注意事項');
    buf.writeln();
    buf.writeln('- 日本語で回答してください');
    buf.writeln('- 季節や気候を考慮した具体的なアドバイスをしてください');
    buf.writeln('- 可能であれば、具体的な時期（月や旬）を示してください');
    buf.writeln('- 不確かな情報は推測であることを明記してください');
    buf.writeln();

    return buf.toString();
  }

  /// Generate a system prompt (shorter) from the profile for direct API use.
  static String generateSystemPrompt(GrowProfile profile) {
    final method =
        farmingMethods[profile.farmingMethod] ?? profile.farmingMethod;
    final exp =
        experienceLevels[profile.experience] ?? profile.experience;
    final crops = profile.crops.join('、');

    final buf = StringBuffer();
    buf.writeln('あなたは栽培の専門家コワーカーです。');
    buf.writeln();
    buf.writeln('ユーザー: $exp。$method。');
    buf.writeln('栽培作物: $crops');
    buf.writeln('場所: ${profile.location}');
    if (profile.challenges.isNotEmpty) {
      buf.writeln('課題: ${profile.challenges}');
    }
    buf.writeln();
    buf.writeln('具体的で実践的なアドバイスを日本語で回答してください。');

    if (profile.farmingMethod == 'natural') {
      buf.writeln('自然農の原則（不耕起・無施肥・無農薬）を尊重してください。');
    } else if (profile.farmingMethod == 'organic') {
      buf.writeln('有機農業の基準に準拠したアドバイスをしてください。');
    }

    buf.writeln();
    buf.writeln('重要: 柔らかい日本野菜が育ちにくい土壌・気候の場合、イタリア野菜（地中海野菜）への転換を提案してください。');
    buf.writeln('硬い野菜は失敗ではなく、オリーブオイルで加熱すれば旨味が凝縮した野菜です。');
    buf.writeln('粘土質・乾燥地にはアーティチョーク、チコリ、カボチャ等が適しています。');
    buf.writeln('調理法も一緒に提案してください。');

    return buf.toString();
  }
}
