/// Generates a personalized cultivation AI skill file (Markdown)
/// based on user's answers to simple questions.
/// 有機農業（自然栽培を含む）専用。

import 'dart:convert';

/// 栽培方式を4軸で定義する
class FarmingPractices {
  final String fertilizer; // 肥料
  final String pesticide; // 農薬
  final String tillage; // 耕起
  final String cover; // 被覆

  const FarmingPractices({
    this.fertilizer = '',
    this.pesticide = '',
    this.tillage = '',
    this.cover = '',
  });

  bool get isEmpty =>
      fertilizer.isEmpty &&
      pesticide.isEmpty &&
      tillage.isEmpty &&
      cover.isEmpty;

  bool get isNotEmpty => !isEmpty;

  /// JSON文字列にシリアライズ
  String toJsonString() => jsonEncode({
        'fertilizer': fertilizer,
        'pesticide': pesticide,
        'tillage': tillage,
        'cover': cover,
      });

  /// JSON文字列からデシリアライズ。旧形式（"natural" 等）にも対応
  factory FarmingPractices.fromString(String? value) {
    if (value == null || value.isEmpty) return const FarmingPractices();
    if (value.startsWith('{')) {
      try {
        final map = jsonDecode(value) as Map<String, dynamic>;
        return FarmingPractices(
          fertilizer: (map['fertilizer'] as String?) ?? '',
          pesticide: (map['pesticide'] as String?) ?? '',
          tillage: (map['tillage'] as String?) ?? '',
          cover: (map['cover'] as String?) ?? '',
        );
      } catch (_) {
        return const FarmingPractices();
      }
    }
    // 旧形式からの変換
    return _migrateLegacy(value);
  }

  /// 旧 farming_method 値を4軸に変換
  static FarmingPractices _migrateLegacy(String legacy) {
    switch (legacy) {
      case 'natural':
        return const FarmingPractices(
          fertilizer: 'none',
          pesticide: 'none',
          tillage: 'no_till',
          cover: 'grass',
        );
      case 'organic':
        return const FarmingPractices(
          fertilizer: 'compost',
          pesticide: 'none',
          tillage: 'till',
          cover: 'mulch',
        );
      case 'permaculture':
        return const FarmingPractices(
          fertilizer: 'green_manure',
          pesticide: 'none',
          tillage: 'no_till',
          cover: 'cover_crop',
        );
      default:
        return const FarmingPractices();
    }
  }

  /// 表示用のサマリー文字列
  String toDisplayString() {
    final parts = <String>[];
    final fLabel = SkillFileGenerator.fertilizerOptions[fertilizer];
    final pLabel = SkillFileGenerator.pesticideOptions[pesticide];
    final tLabel = SkillFileGenerator.tillageOptions[tillage];
    final cLabel = SkillFileGenerator.coverOptions[cover];
    if (fLabel != null) parts.add(fLabel);
    if (pLabel != null) parts.add(pLabel);
    if (tLabel != null) parts.add(tLabel);
    if (cLabel != null) parts.add(cLabel);
    return parts.join('・');
  }

  /// 短い表示用（2項目程度）
  String toShortString() {
    final parts = <String>[];
    final fLabel = SkillFileGenerator.fertilizerOptions[fertilizer];
    final pLabel = SkillFileGenerator.pesticideOptions[pesticide];
    if (fLabel != null) parts.add(fLabel);
    if (pLabel != null) parts.add(pLabel);
    return parts.isEmpty ? '未設定' : parts.join('・');
  }
}

class GrowProfile {
  final List<String> crops;
  final String location;
  final FarmingPractices practices;
  final String experience;
  final String challenges;

  GrowProfile({
    required this.crops,
    required this.location,
    required this.practices,
    required this.experience,
    required this.challenges,
  });

  Map<String, dynamic> toMap() => {
        'crops': crops,
        'location': location,
        'farming_method': practices.toJsonString(),
        'experience': experience,
        'challenges': challenges,
      };
}

class SkillFileGenerator {
  // -- 4軸の選択肢 --

  static const fertilizerOptions = {
    'none': '無施肥（自然の循環のみ）',
    'compost': '堆肥（植物性・動物性）',
    'green_manure': '緑肥（すき込み）',
    'bokashi': 'ぼかし肥料',
  };

  static const pesticideOptions = {
    'none': '無農薬',
    'organic_certified': '有機JAS認定資材のみ',
  };

  static const tillageOptions = {
    'no_till': '不耕起',
    'minimum_till': '部分耕起',
    'till': '耕起',
  };

  static const coverOptions = {
    'grass': '草生栽培',
    'mulch': 'マルチ（敷きわら等）',
    'cover_crop': 'カバークロップ',
    'none': '被覆なし',
  };

  static const experienceLevels = {
    'beginner': '初心者（1年未満）',
    'intermediate': '中級者（1〜3年）',
    'experienced': '経験者（3〜10年）',
    'expert': '熟練者（10年以上）',
  };

  /// Generate a Markdown skill file from the user profile.
  static String generate(GrowProfile profile) {
    final buf = StringBuffer();
    final p = profile.practices;

    buf.writeln('# 栽培AIスキルファイル');
    buf.writeln();
    buf.writeln('> このファイルをAIアシスタントのシステムプロンプトや');
    buf.writeln('> カスタム指示に貼り付けると、あなた専用の栽培アドバイザーになります。');
    buf.writeln('> Generated by AIseed Grow（有機農業専用）');
    buf.writeln();

    // Role definition
    buf.writeln('## あなたの役割');
    buf.writeln();
    buf.writeln('あなたは有機農業（自然栽培を含む）の専門家アシスタントです。');
    buf.writeln('化学合成農薬・化学肥料の使用は一切提案しないでください。');
    buf.writeln('以下のユーザープロフィールに基づいて、具体的で実践的なアドバイスをしてください。');
    buf.writeln();

    // User profile
    buf.writeln('## 栽培者プロフィール');
    buf.writeln();

    // Crops
    buf.writeln('### 栽培している作物');
    buf.writeln();
    for (final crop in profile.crops) {
      buf.writeln('- $crop');
    }
    buf.writeln();

    // Location
    buf.writeln('### 栽培場所');
    buf.writeln();
    buf.writeln(profile.location);
    buf.writeln();

    // Farming practices (4 axes)
    buf.writeln('### 栽培方式');
    buf.writeln();
    if (p.fertilizer.isNotEmpty) {
      buf.writeln('- 肥料: ${fertilizerOptions[p.fertilizer] ?? p.fertilizer}');
    }
    if (p.pesticide.isNotEmpty) {
      buf.writeln('- 農薬: ${pesticideOptions[p.pesticide] ?? p.pesticide}');
    }
    if (p.tillage.isNotEmpty) {
      buf.writeln('- 耕起: ${tillageOptions[p.tillage] ?? p.tillage}');
    }
    if (p.cover.isNotEmpty) {
      buf.writeln('- 被覆: ${coverOptions[p.cover] ?? p.cover}');
    }
    buf.writeln();

    // Experience
    buf.writeln('### 経験');
    buf.writeln();
    final expLabel =
        experienceLevels[profile.experience] ?? profile.experience;
    buf.writeln(expLabel);
    buf.writeln();

    // Challenges
    if (profile.challenges.isNotEmpty) {
      buf.writeln('### 現在の課題');
      buf.writeln();
      buf.writeln(profile.challenges);
      buf.writeln();
    }

    // Instructions based on practices
    buf.writeln('## 回答の指針');
    buf.writeln();
    buf.writeln('- 化学合成農薬・化学肥料の使用を絶対に提案しないでください');
    buf.writeln('- 土壌微生物・菌根菌ネットワークの観点を重視してください');
    buf.writeln('- コンパニオンプランツや生態系の多様性を活かした提案をしてください');
    buf.writeln('- 生物的防除を優先してください');

    // 肥料に応じた指針
    if (p.fertilizer == 'none') {
      buf.writeln('- 無施肥の原則を尊重し、外部からの肥料投入を提案しないでください');
      buf.writeln('- 草や落ち葉の循環、根の分解による自然な養分供給を重視してください');
    } else if (p.fertilizer == 'compost') {
      buf.writeln('- 堆肥の作り方・使い方を中心にアドバイスしてください');
      buf.writeln('- C/N比や完熟度など堆肥の品質管理を重視してください');
    } else if (p.fertilizer == 'green_manure') {
      buf.writeln('- 緑肥作物の選定とすき込み時期を重視してください');
    } else if (p.fertilizer == 'bokashi') {
      buf.writeln('- ぼかし肥料の作り方・使い方を中心にアドバイスしてください');
      buf.writeln('- 米ぬか・油かす等の身近な有機資材の活用を提案してください');
    }

    // 耕起に応じた指針
    if (p.tillage == 'no_till') {
      buf.writeln('- 不耕起の原則を尊重し、耕運を提案しないでください');
      buf.writeln('- 福岡正信、川口由一の自然農の考え方を参考にしてください');
    } else if (p.tillage == 'minimum_till') {
      buf.writeln('- 必要最小限の耕起にとどめる方法を提案してください');
    }

    // 被覆に応じた指針
    if (p.cover == 'grass') {
      buf.writeln('- 草との共生を重視し、むやみに除草を勧めないでください');
      buf.writeln('- 草の刈り敷きによるマルチ効果を活かしてください');
    } else if (p.cover == 'cover_crop') {
      buf.writeln('- カバークロップの選定と管理を重視してください');
    } else if (p.cover == 'mulch') {
      buf.writeln('- 敷きわら・もみ殻等の有機マルチを活用してください');
    }

    buf.writeln();

    // Experience-based tone
    switch (profile.experience) {
      case 'beginner':
        buf.writeln('- 初心者にもわかりやすく、専門用語には説明を添えてください');
        buf.writeln('- 基本的な手順をステップバイステップで説明してください');
        buf.writeln('- 失敗しにくい方法を優先的に提案してください');
        break;
      case 'intermediate':
        buf.writeln('- 基本は理解しているので、一歩進んだテクニックも含めてください');
        buf.writeln('- 「なぜそうするのか」の理由も説明してください');
        break;
      case 'experienced':
      case 'expert':
        buf.writeln('- 専門的な知識レベルで回答してください');
        buf.writeln('- 科学的根拠やデータも含めて説明してください');
        buf.writeln('- 新しい研究結果や革新的な手法も紹介してください');
        break;
    }

    buf.writeln();

    // Vegetable knowledge base
    buf.writeln('## 日本野菜とイタリア野菜の知識');
    buf.writeln();
    buf.writeln('ユーザーが「柔らかくてみずみずしい野菜を作りたい」と言った場合、');
    buf.writeln('土壌や気候条件によっては難しいことがあります。以下の知識を活用してください。');
    buf.writeln();
    buf.writeln('### 重要な視点の転換');
    buf.writeln('- 硬い野菜＝失敗ではない。イタリア野菜の視点では「旨味が凝縮」している');
    buf.writeln('- 粘土質土壌・乾燥地は日本野菜には不向きだが、地中海野菜には理想的');
    buf.writeln('- 土を変えるより、土に合った作物と調理法を選ぶ方が賢明');
    buf.writeln();
    buf.writeln('### 土壌・気候が厳しい場合のおすすめ作物');
    buf.writeln('- アーティチョーク（深根性、菌根菌共生、多年草）');
    buf.writeln('- チコリ・エンダイブ（キク科、低窒素適応）');
    buf.writeln('- カボチャ・ズッキーニ（乾燥耐性、菌根菌共生）');
    buf.writeln('- トマト・ナス（水を控えると味が濃くなる）');
    buf.writeln('- ルッコラ（辛味と苦味が特徴）');
    buf.writeln();
    buf.writeln('### 科学的背景');
    buf.writeln('- イタリア野菜は乾燥ストレスで糖・ポリフェノール・グルタミン酸を蓄積する');
    buf.writeln('- ペクチンが多いため加熱で「トロトロ」に軟化する（リグニンで硬くなる日本野菜と異なる）');
    buf.writeln('- 菌根菌と共生する科（キク科・ナス科・ウリ科）は痩せ地でも旨味を作れる');
    buf.writeln('- アブラナ科・アカザ科（日本の葉物）は菌根菌と共生せず高窒素が必要');
    buf.writeln();
    buf.writeln('### 調理法も一緒に提案する');
    buf.writeln('- 硬い野菜はオリーブオイルでじっくり加熱すると旨味が引き出される');
    buf.writeln('- 苦味はアク抜きせず、油脂と合わせると深みに変わる');
    buf.writeln('- 日本料理の調理法（生食・軽い加熱）は柔らかい日本野菜向け');
    buf.writeln();

    // General guidelines
    buf.writeln('## 一般的な注意事項');
    buf.writeln();
    buf.writeln('- 日本語で回答してください');
    buf.writeln('- 季節や気候を考慮した具体的なアドバイスをしてください');
    buf.writeln('- 可能であれば、具体的な時期（月や旬）を示してください');
    buf.writeln('- 不確かな情報は推測であることを明記してください');
    buf.writeln();

    return buf.toString();
  }

  /// Generate a system prompt (shorter) from the profile for direct API use.
  static String generateSystemPrompt(GrowProfile profile) {
    final p = profile.practices;
    final exp =
        experienceLevels[profile.experience] ?? profile.experience;
    final crops = profile.crops.join('、');

    final buf = StringBuffer();
    buf.writeln('あなたは有機農業（自然栽培を含む）の専門家コワーカーです。');
    buf.writeln('化学合成農薬・化学肥料は一切提案しないでください。');
    buf.writeln();
    buf.writeln('ユーザー: $exp。');
    buf.writeln('栽培方式: ${p.toDisplayString()}');
    buf.writeln('栽培作物: $crops');
    buf.writeln('場所: ${profile.location}');
    if (profile.challenges.isNotEmpty) {
      buf.writeln('課題: ${profile.challenges}');
    }
    buf.writeln();
    buf.writeln('具体的で実践的なアドバイスを日本語で回答してください。');

    if (p.fertilizer == 'none') {
      buf.writeln('無施肥の原則を尊重してください。');
    }
    if (p.tillage == 'no_till') {
      buf.writeln('不耕起の原則を尊重してください。');
    }
    if (p.cover == 'grass') {
      buf.writeln('草生栽培の原則を尊重してください。');
    }

    buf.writeln();
    buf.writeln('重要: 柔らかい日本野菜が育ちにくい土壌・気候の場合、イタリア野菜（地中海野菜）への転換を提案してください。');
    buf.writeln('硬い野菜は失敗ではなく、オリーブオイルで加熱すれば旨味が凝縮した野菜です。');
    buf.writeln('粘土質・乾燥地にはアーティチョーク、チコリ、カボチャ等が適しています。');
    buf.writeln('調理法も一緒に提案してください。');

    return buf.toString();
  }
}
