"""Skill file generation endpoint.

Generates a personalized Markdown AI skill file from a simple questionnaire.
Can be used without login (for demos / hackathons).
"""

from fastapi import APIRouter
from pydantic import BaseModel

router = APIRouter(prefix="/skillfile", tags=["skillfile"])

FARMING_METHODS = {
    "natural": "自然農（不耕起・無施肥・無農薬）",
    "organic": "有機農業（有機肥料・無農薬）",
    "conventional": "慣行農業",
    "permaculture": "パーマカルチャー",
    "other": "その他",
}

EXPERIENCE_LEVELS = {
    "beginner": "初心者（1年未満）",
    "intermediate": "中級者（1〜3年）",
    "experienced": "経験者（3〜10年）",
    "expert": "熟練者（10年以上）",
}


class SkillFileRequest(BaseModel):
    crops: list[str]
    location: str
    farming_method: str
    experience: str
    challenges: str = ""


class SkillFileResponse(BaseModel):
    skill_file: str
    system_prompt: str


def _generate_skill_file(req: SkillFileRequest) -> str:
    lines = []
    lines.append("# 栽培AIスキルファイル\n")
    lines.append("> このファイルをAIアシスタントのシステムプロンプトや")
    lines.append("> カスタム指示に貼り付けると、あなた専用の栽培アドバイザーになります。")
    lines.append("> Generated by AIseed Grow\n")

    lines.append("## あなたの役割\n")
    lines.append("あなたは栽培の専門家アシスタントです。")
    lines.append("以下のユーザープロフィールに基づいて、具体的で実践的なアドバイスをしてください。\n")

    lines.append("## 栽培者プロフィール\n")

    lines.append("### 栽培している作物\n")
    for crop in req.crops:
        lines.append(f"- {crop}")
    lines.append("")

    lines.append("### 栽培場所\n")
    lines.append(f"{req.location}\n")

    lines.append("### 農法\n")
    method = FARMING_METHODS.get(req.farming_method, req.farming_method)
    lines.append(f"{method}\n")

    lines.append("### 経験\n")
    exp = EXPERIENCE_LEVELS.get(req.experience, req.experience)
    lines.append(f"{exp}\n")

    if req.challenges:
        lines.append("### 現在の課題\n")
        lines.append(f"{req.challenges}\n")

    lines.append("## 回答の指針\n")

    if req.farming_method == "natural":
        lines.append("- 自然農の原則（不耕起・無施肥・無農薬・草との共生）を尊重してください")
        lines.append("- 化学肥料や農薬の使用を提案しないでください")
        lines.append("- 土壌微生物・菌根菌ネットワークの観点を重視してください")
        lines.append("- コンパニオンプランツや生態系の多様性を活かした提案をしてください")
        lines.append("- 福岡正信、川口由一の自然農の考え方を参考にしてください")
    elif req.farming_method == "organic":
        lines.append("- 有機JAS基準に準拠したアドバイスをしてください")
        lines.append("- 化学合成農薬・化学肥料の使用を提案しないでください")
        lines.append("- 堆肥、緑肥、有機質肥料を活用した提案をしてください")
        lines.append("- 生物的防除やコンパニオンプランツを優先してください")
    elif req.farming_method == "permaculture":
        lines.append("- パーマカルチャーの倫理（地球への配慮・人への配慮・余剰の共有）を基本にしてください")
        lines.append("- 多年生植物、フォレストガーデン、ギルドの概念を取り入れてください")
        lines.append("- 水の循環、エネルギー効率、生態系デザインを考慮してください")
    else:
        lines.append("- 効率と品質のバランスを考えた実践的なアドバイスをしてください")
        lines.append("- 農薬使用時は適切な使用量と安全な使用方法を明記してください")

    lines.append("")

    if req.experience == "beginner":
        lines.append("- 初心者にもわかりやすく、専門用語には説明を添えてください")
        lines.append("- 基本的な手順をステップバイステップで説明してください")
        lines.append("- 失敗しにくい方法を優先的に提案してください")
    elif req.experience == "intermediate":
        lines.append("- 基本は理解しているので、一歩進んだテクニックも含めてください")
        lines.append("- 「なぜそうするのか」の理由も説明してください")
    else:
        lines.append("- 専門的な知識レベルで回答してください")
        lines.append("- 科学的根拠やデータも含めて説明してください")
        lines.append("- 新しい研究結果や革新的な手法も紹介してください")

    lines.append("")

    lines.append("## 日本野菜とイタリア野菜の知識\n")
    lines.append("ユーザーが「柔らかくてみずみずしい野菜を作りたい」と言った場合、")
    lines.append("土壌や気候条件によっては難しいことがあります。以下の知識を活用してください。\n")
    lines.append("### 重要な視点の転換")
    lines.append("- 硬い野菜＝失敗ではない。イタリア野菜の視点では「旨味が凝縮」している")
    lines.append("- 粘土質土壌・乾燥地は日本野菜には不向きだが、地中海野菜には理想的")
    lines.append("- 土を変えるより、土に合った作物と調理法を選ぶ方が賢明\n")
    lines.append("### 土壌・気候が厳しい場合のおすすめ作物")
    lines.append("- アーティチョーク（深根性、菌根菌共生、多年草）")
    lines.append("- チコリ・エンダイブ（キク科、低窒素適応）")
    lines.append("- カボチャ・ズッキーニ（乾燥耐性、菌根菌共生）")
    lines.append("- トマト・ナス（水を控えると味が濃くなる）")
    lines.append("- ルッコラ（辛味と苦味が特徴）\n")
    lines.append("### 科学的背景")
    lines.append("- イタリア野菜は乾燥ストレスで糖・ポリフェノール・グルタミン酸を蓄積する")
    lines.append("- ペクチンが多いため加熱で「トロトロ」に軟化する（リグニンで硬くなる日本野菜と異なる）")
    lines.append("- 菌根菌と共生する科（キク科・ナス科・ウリ科）は痩せ地でも旨味を作れる")
    lines.append("- アブラナ科・アカザ科（日本の葉物）は菌根菌と共生せず高窒素が必要\n")
    lines.append("### 調理法も一緒に提案する")
    lines.append("- 硬い野菜はオリーブオイルでじっくり加熱すると旨味が引き出される")
    lines.append("- 苦味はアク抜きせず、油脂と合わせると深みに変わる")
    lines.append("- 日本料理の調理法（生食・軽い加熱）は柔らかい日本野菜向け")
    lines.append("")

    lines.append("## 一般的な注意事項\n")
    lines.append("- 日本語で回答してください")
    lines.append("- 季節や気候を考慮した具体的なアドバイスをしてください")
    lines.append("- 可能であれば、具体的な時期（月や旬）を示してください")
    lines.append("- 不確かな情報は推測であることを明記してください")
    lines.append("")

    return "\n".join(lines)


def _generate_system_prompt(req: SkillFileRequest) -> str:
    method = FARMING_METHODS.get(req.farming_method, req.farming_method)
    exp = EXPERIENCE_LEVELS.get(req.experience, req.experience)
    crops = "、".join(req.crops)

    parts = [
        "あなたは栽培の専門家コワーカーです。",
        "",
        f"ユーザー: {exp}。{method}。",
        f"栽培作物: {crops}",
        f"場所: {req.location}",
    ]
    if req.challenges:
        parts.append(f"課題: {req.challenges}")
    parts.append("")
    parts.append("具体的で実践的なアドバイスを日本語で回答してください。")

    if req.farming_method == "natural":
        parts.append("自然農の原則（不耕起・無施肥・無農薬）を尊重してください。")
    elif req.farming_method == "organic":
        parts.append("有機農業の基準に準拠したアドバイスをしてください。")

    parts.append("")
    parts.append("重要: 柔らかい日本野菜が育ちにくい土壌・気候の場合、イタリア野菜（地中海野菜）への転換を提案してください。")
    parts.append("硬い野菜は失敗ではなく、オリーブオイルで加熱すれば旨味が凝縮した野菜です。")
    parts.append("粘土質・乾燥地にはアーティチョーク、チコリ、カボチャ等が適しています。")
    parts.append("調理法も一緒に提案してください。")

    return "\n".join(parts)


@router.post("/generate", response_model=SkillFileResponse)
async def generate_skill_file(req: SkillFileRequest):
    """Generate a personalized Markdown skill file.

    No login required - works for demos and hackathons.
    """
    return SkillFileResponse(
        skill_file=_generate_skill_file(req),
        system_prompt=_generate_system_prompt(req),
    )
